# --------------------------------------------------
# Commands to run this compose file:
#     - docker-compose -p student-wellness-hub -f docker-compose.yml up -d
#       → Starts all containers in detached mode (without rebuilding images)
#
#     - docker-compose -p student-wellness-hub -f docker-compose.yml up -d --build
#       → Forces rebuild of all images before starting containers
# --------------------------------------------------

services:

  postgres:
    container_name: postgres-wellness
    image: postgres
    environment:
      POSTGRES_DB: wellness_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./docker/postgres/data:/data/postgres
      - ./docker/postgres/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - wellness-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongodb-wellness
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./docker/mongo/data:/data/db
      - ./docker/mongo/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    command: mongod --auth
    networks:
      - wellness-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis-wellness
    networks:
      - wellness-network

  wellness-resource-service:
    image: wellness-resource-service
    ports:
      - "8081:8081"
    build:
      context: ./wellness-resource-service
      dockerfile: ./Dockerfile
    container_name: wellness-resource-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-wellness:5432/wellness_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATA_REDIS_HOST=redis-wellness
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_CACHE_TYPE=redis
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - redis
    networks:
      - wellness-network
    # had to look up a way to fix these containers crashing due to boot order
    restart: unless-stopped

  goal-tracking-service:
    image: goal-tracking-service
    ports:
      - "8082:8082"
    build:
      context: ./goal-tracking-service
      dockerfile: ./Dockerfile
    container_name: goal-tracking-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:password@mongodb-wellness:27017/goals_db?authSource=admin
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb
    networks:
      - wellness-network
    # had to look up a way to fix these containers crashing due to boot order
    restart: unless-stopped

  event-service:
    image: event-service
    ports:
      - "8083:8083"
    build:
      context: ./event-service
      dockerfile: ./Dockerfile
    container_name: event-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-wellness:5432/wellness_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
    networks:
      - wellness-network
    # had to look up a way to fix these containers crashing due to boot order
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    ports:
      - "8085:8081"
    container_name: mongo-express-wellness
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb-wellness
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    depends_on:
      - mongodb
    networks:
      - wellness-network

  pgadmin:
    image: dpage/pgadmin4:9.2
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password
    container_name: pgadmin-wellness
    networks:
      - wellness-network

# Optional volumes section for persisting data
volumes:
  mongo-db:
    driver: local

networks:
  wellness-network:
    driver: bridge