# --------------------------------------------------
# Commands to run this compose file:
#     - docker-compose -p student-wellness-hub -f docker-compose.yml up -d
#       → Starts all containers in detached mode (without rebuilding images)
#
#     - docker-compose -p student-wellness-hub -f docker-compose.yml up -d --build
#       → Forces rebuild of all images before starting containers
# --------------------------------------------------

services:

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak-wellness
    command:
      - start-dev
      - --hostname=keycloak-wellness
      - --hostname-port=8080
      - --hostname-strict=false
      - --hostname-strict-backchannel=false
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-wellness:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: keycloak-wellness
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
    ports:
      - "8090:8080"
    depends_on:
      - postgres
    networks:
      - wellness-network
    restart: unless-stopped

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak-wellness:8080/realms/wellness-hub
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak-wellness:8080/realms/wellness-hub/protocol/openid-connect/certs
    depends_on:
      - keycloak
      - wellness-resource-service
      - goal-tracking-service
      - event-service
    networks:
      - wellness-network
    restart: unless-stopped

  postgres:
    container_name: postgres-wellness
    image: postgres
    environment:
      POSTGRES_DB: wellness_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./docker/postgres/data:/data/postgres
      - ./docker/postgres/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - wellness-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongodb-wellness
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./docker/mongo/data:/data/db
      - ./docker/mongo/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    command: mongod --auth
    networks:
      - wellness-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis-wellness
    networks:
      - wellness-network

  # Kafka & Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper-wellness
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - wellness-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-wellness
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-wellness:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-wellness:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - wellness-network

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    container_name: schema-registry-wellness
    depends_on:
      - kafka
    ports:
      - "8092:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-wellness
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-wellness:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    networks:
      - wellness-network

  wellness-resource-service:
    image: wellness-resource-service
    ports:
      - "8084:8081"
    build:
      context: ./wellness-resource-service
      dockerfile: ./Dockerfile
    container_name: wellness-resource-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-wellness:5432/wellness_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATA_REDIS_HOST=redis-wellness
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_CACHE_TYPE=redis
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-wellness:9092
      - SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL=http://schema-registry-wellness:8081
    depends_on:
      - postgres
      - redis
      - kafka
      - schema-registry
    networks:
      - wellness-network
    restart: unless-stopped

  goal-tracking-service:
    image: goal-tracking-service
    ports:
      - "8082:8082"
    build:
      context: ./goal-tracking-service
      dockerfile: ./Dockerfile
    container_name: goal-tracking-service
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:password@mongodb-wellness:27017/goals_db?authSource=admin
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-wellness:9092
      - SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL=http://schema-registry-wellness:8081
    depends_on:
      - mongodb
      - kafka
      - schema-registry
    networks:
      - wellness-network
    restart: unless-stopped

  event-service:
    image: event-service
    ports:
      - "8083:8083"
    build:
      context: ./event-service
      dockerfile: ./Dockerfile
    container_name: event-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-wellness:5432/wellness_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-wellness:9092
      - SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL=http://schema-registry-wellness:8081
    depends_on:
      - postgres
      - kafka
      - schema-registry
    networks:
      - wellness-network
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    ports:
      - "8085:8081"
    container_name: mongo-express-wellness
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb-wellness
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    depends_on:
      - mongodb
    networks:
      - wellness-network

  pgadmin:
    image: dpage/pgadmin4:9.2
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password
    container_name: pgadmin-wellness
    networks:
      - wellness-network

volumes:
  mongo-db:
    driver: local

networks:
  wellness-network:
    driver: bridge