# --------------------------------------------------
# Commands to run this compose file:
#     - docker-compose -p student-wellness-hub -f docker-compose.yml up -d
#       → Starts all containers in detached mode (without rebuilding images)
#
#     - docker-compose -p student-wellness-hub -f docker-compose.yml up -d --build
#       → Forces rebuild of all images before starting containers
# --------------------------------------------------

services:

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_DB=wellness_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    volumes:
      - ./docker/postgres/data:/data/postgres
      - ./docker/postgres/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wellness-network

  mongodb:
    image: mongo:7
    container_name: mongodb-student-wellness
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./docker/mongo/data:/data/db
      - ./docker/mongo/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27017:27017"
    command: mongod --auth
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wellness-network

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wellness-network

  wellness-resource-service:
    build:
      context: ./wellness-resource-service
      dockerfile: ./Dockerfile
    image: wellness-resource-service
    container_name: wellness-resource-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=wellness_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=8081
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    networks:
      - wellness-network

  goal-tracking-service:
    build:
      context: ./goal-tracking-service
      dockerfile: ./Dockerfile
    image: goal-tracking-service
    container_name: goal-tracking-service
    ports:
      - "8082:8082"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=goals_db
      - SERVER_PORT=8082
    depends_on:
      mongodb:
        condition: service_healthy
    restart: on-failure
    networks:
      - wellness-network

  event-service:
    build:
      context: ./event-service
      dockerfile: ./Dockerfile
    image: event-service
    container_name: event-service
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=wellness_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SERVER_PORT=8083
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    networks:
      - wellness-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8085:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    depends_on:
      - mongodb
    networks:
      - wellness-network

  pgadmin:
    image: dpage/pgadmin4:9.2
    container_name: pgadmin
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - postgres
    networks:
      - wellness-network

volumes:
  postgres-data:
    driver: local
  mongo-data:
    driver: local

networks:
  wellness-network:
    driver: bridge
